#!/bin/bash

# Create the dev database (prod gets created automatically)
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE ${DB_NAME}_dev;"

# Create users
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "
CREATE USER ${DB_USER_R} WITH PASSWORD '${DB_USER_R_PASSWORD}';
CREATE USER ${DB_USER_RW} WITH PASSWORD '${DB_USER_RW_PASSWORD}';
"

# Add the users to the databases
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DB_USER_R};
GRANT USAGE ON SCHEMA public TO ${DB_USER_R};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_USER_R};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DB_USER_RW};
GRANT USAGE ON SCHEMA public TO ${DB_USER_RW};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_USER_RW};
"

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "
GRANT CONNECT ON DATABASE ${DB_NAME}_dev TO ${DB_USER_R};
GRANT USAGE ON SCHEMA public TO ${DB_USER_R};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_USER_R};
GRANT CONNECT ON DATABASE ${DB_NAME}_dev TO ${DB_USER_RW};
GRANT USAGE ON SCHEMA public TO ${DB_USER_RW};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_USER_RW};
"
