name: Publish Api And MqttService And GraphQL

on:
  workflow_dispatch: # manual trigger
  create:
    branches:
      - 'live'

permissions:
  contents: read

jobs:
  build-publish_api:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/UCLL.Projects.WeatherStations.Api/Dockerfile
          push: true
          tags: |
            docker.io/weatherstations/weatherstations-api:latest
            docker.io/weatherstations/weatherstations-api:${{ github.sha }}
      -
        name: Log out from Docker Hub
        run: docker logout

  build-publish_mqttservice:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/UCLL.Projects.WeatherStations.MqttService/Dockerfile
          push: true
          tags: |
            docker.io/weatherstations/weatherstations-mqtt-service:latest
            docker.io/weatherstations/weatherstations-mqtt-service:${{ github.sha }}
      -
        name: Log out from Docker Hub
        run: docker logout

  build-publish_graphql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/UCLL.Projects.WeatherStations.GraphQL/Dockerfile
          push: true
          tags: |
            docker.io/weatherstations/weatherstations-graphql:latest
            docker.io/weatherstations/weatherstations-graphql:${{ github.sha }}
      - name: Log out from Docker Hub
        run: docker logout