name: Publish WebApi And MQTT

on:
  workflow_dispatch: # manual trigger
  create:
    branches:
      - 'live'

permissions:
  contents: read

jobs:
  build-publish_webapi:
    uses: ./.github/workflows/publish_webapi.yml

  build-publish_mqtt:
    uses: ./.github/workflows/publish_mqtt.yml
