name: Publish MqttService

on:
  workflow_dispatch: # manual trigger
  pull_request:
    types: [closed]
    branches:
      - 'live'
    paths:
      - 'src/UCLL.Projects.WeatherStations.MqttService/**'
      - 'src/UCLL.Projects.WeatherStations.Shared/**'

permissions:
  contents: read

jobs:
  build-publish_mqttservice:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'live'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/UCLL.Projects.WeatherStations.MqttService/Dockerfile
          push: true
          tags: |
            docker.io/weatherstations/weatherstations-mqtt-service:latest
            docker.io/weatherstations/weatherstations-mqtt-service:${{ github.sha }}
      - # good practice (for when multiple jobs)
        name: Log out from Docker Hub
        run: docker logout