name: Publish WebApi And MQTT

on:
  workflow_dispatch: # manual trigger
  create:
    branches:
      - ['live']

permissions:
  id-token: write
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - "docker.io/weatherstations/ucll.projects.weatherstations.webapi"
          - "docker.io/weatherstations/ucll.projects.weatherstations.mqtt"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: |
            ${{ matrix.tags }}:latest
            ${{ matrix.tags }}:${{ github.sha }}
      
      - name: Log out from Docker Hub
        run: docker logout
